dist: trusty
sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libx11-xcb-dev libxcb-ewmh-dev libasound2-dev libpango1.0-dev libcairo2-dev libpangocairo-1.0-0
