dist: trusty
sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

before_script:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo install --force clippy ; fi

script:
  - cargo build
  - cargo test
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo clippy ; fi

addons:
  apt:
    packages:
      - libx11-xcb-dev
      - libxcb-ewmh-dev
      - libasound2-dev
      - libpango1.0-dev
      - libcairo2-dev
