dist: trusty
sudo: required

services:
  - xvfb

language: rust

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add clippy

script:
  - cargo build
  - xvfb-run cargo test
  - cargo clippy

addons:
  apt:
    packages:
      - libx11-xcb-dev
      - libxcb-ewmh-dev
      - libasound2-dev
      - libpango1.0-dev
      - libcairo2-dev
