[package]
name = "cnx"
version = "0.1.0"
authors = ["Michael Killough <michaeljkillough@gmail.com>"]
description = "A simple X11 status bar"
repository = "https://github.com/mjkillough/cnx"
readme = "README.md"
keywords = ["x11", "status", "bar"]
categories = ["gui"]
license = "MIT"

[badges]
travis-ci = { repository = "mjkillough/cnx", branch = "master" }

[[bin]]
name = "cnx"
doc = false

[dependencies]
alsa = "0.1"
cairo-rs = { version = "0.2", features = ["xcb"] }
cairo-sys-rs = "0.4"
chrono = "0.4"
error-chain = "0.10"
futures = "0.1"
lazy_static = "0.2"
libc = "0.2"
mio = "0.6"
pango = "0.2"
pangocairo = "0.2"
regex = "0.2"
tokio-core = "0.1"
tokio-timer = "0.1"
xcb = "0.8"
xcb-util = { version = "0.2", features = ["ewmh"] }
