[package]
name = "cnx"
version = "0.1.0"
authors = ["Michael Killough <michaeljkillough@gmail.com>"]
description = "A simple X11 status bar"
homepage = "https://github.com/mjkillough/cnx"
repository = "https://github.com/mjkillough/cnx"
readme = "README.md"
keywords = ["x11", "status", "bar"]
categories = ["gui"]
license = "MIT"

[badges]
travis-ci = { repository = "mjkillough/cnx", branch = "master" }

[[bin]]
name = "cnx"

[dependencies]
alsa = "0.1"
chrono = "0.3"
error-chain = "0.10"
futures = "0.1"
lazy_static = "0.2"
libc = "0.2"
mio = "0.6"
regex = "0.2"
tokio-core = "0.1"
tokio-timer = "0.1"
xcb = { version = "0.7.6", path = "./xcb", features = ["thread"] }

[dependencies.xcb-util]
version = "0.1.8"
path = "./xcb-util"
features = ["ewmh"]

# We need the git version of gtk-rs packages so that we can have the fix for
# gtk-rs/cairo#130.
[dependencies.cairo-rs]
git = "https://github.com/gtk-rs/cairo"
default-features = false
features = ["xcb"]

[dependencies.cairo-sys-rs]
git = "https://github.com/gtk-rs/cairo"

[dependencies.pango]
git = "https://github.com/gtk-rs/pango"


# We include pangocairo as a submodule so that we can modify it to also use
# the git version of gtk-rs packages.
[dependencies.pangocairo]
version = "0.1.3"
path = "./pangocairo"
