[package]
name = "huế"
version = "0.1.0"
authors = ["Michael Killough <michaeljkillough@gmail.com>"]

[dependencies]
chrono = "0.3.1"
mio = "0.6.9"
tokio-core = "0.1.8"
tokio-timer = "0.1.1"
futures = "0.1.14"
alsa = "0.1.8"
libc = "0.2.23"

[dependencies.xcb]
version = "0.7.6"
features = ["xlib_xcb"]

[dependencies.xcb-util]
path = "./xcb-util"
features = ["ewmh"]

# We need the git version of gtk-rs packages so that we can have the fix for
# gtk-rs/cairo#130.
[dependencies.cairo-rs]
git = "https://github.com/gtk-rs/cairo"
default-features = false
features = ["xcb"]

[dependencies.cairo-sys-rs]
git = "https://github.com/gtk-rs/cairo"

[dependencies.pango]
git = "https://github.com/gtk-rs/pango"


# We include pangocairo as a submodule so that we can modify it to also use
# the git version of gtk-rs packages.
[dependencies.pangocairo]
path = "./pangocairo"
